config/routes.rb
Rails.application.routes.draw do
  root to: "books#index"
  resources :books
  resources :shelves do
    get 'books', to: "books#list_by_shelves"
  end
  resources :authors do
    get 'books', to: "books#list_by_author"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates_presence_of :name, :last_name
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :shelf
  validates_presence_of :title, :editorial, :isbn
  validates :author, presence: true
  validates :shelf, presence: true  
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  validates_presence_of :levels, :pasillo
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :last_name, :nacionality, :review)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @title = "Books"
    @books = Book.all
  end
  
  # GET /authors/:author_id/books
  def list_by_author
    author = Author.find(params[:author_id])
    @title = "Books - By #{author.name}"
    @books = Book.where(author_id: params[:author_id])
    render :index
  end

  # GET /authors/:shelf_id/books
  def list_by_shelves
    shelf = Shelf.find(params[:shelf_id])
    @title = "Books - (ID #{shelf.id})/#{shelf.pasillo}"
    @books = Book.where(shelf_id: params[:shelf_id])
    render :index
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @shelves = Shelf.all
    @authors = Author.all
  end

  # GET /books/1/edit
  def edit
    @shelves = Shelf.all
    @authors = Author.all
  end

  # POST /books
  # POST /books.json
  def create
    @shelves = Shelf.all
    @authors = Author.all
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :editorial, :year_edition, :isbn, :author_id, :shelf_id, :num_edition)
    end
end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController
  before_action :set_shelf, only: [:show, :edit, :update, :destroy]

  # GET /shelves
  # GET /shelves.json
  def index
    @shelves = Shelf.all
  end

  # GET /shelves/1
  # GET /shelves/1.json
  def show
  end

  # GET /shelves/new
  def new
    @shelf = Shelf.new
  end

  # GET /shelves/1/edit
  def edit
  end

  # POST /shelves
  # POST /shelves.json
  def create
    @shelf = Shelf.new(shelf_params)

    respond_to do |format|
      if @shelf.save
        format.html { redirect_to @shelf, notice: 'Shelf was successfully created.' }
        format.json { render :show, status: :created, location: @shelf }
      else
        format.html { render :new }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shelves/1
  # PATCH/PUT /shelves/1.json
  def update
    respond_to do |format|
      if @shelf.update(shelf_params)
        format.html { redirect_to @shelf, notice: 'Shelf was successfully updated.' }
        format.json { render :show, status: :ok, location: @shelf }
      else
        format.html { render :edit }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shelves/1
  # DELETE /shelves/1.json
  def destroy
    @shelf.destroy
    respond_to do |format|
      format.html { redirect_to shelves_url, notice: 'Shelf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shelf
      @shelf = Shelf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shelf_params
      params.require(:shelf).permit(:pasillo, :levels)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :nacionality %>
    <%= form.text_field :nacionality, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-xs btn-success" %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="container">
  <h1>Editing Author</h1>

  <%= render 'form', author: @author %>

  <%= link_to 'Show', @author %> |
  <%= link_to 'Back', authors_path %>
</div>

app/views/authors/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Authors</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Last name</th>
        <th>Nacionality</th>
        <th>Review</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <td><%= author.name %></td>
          <td><%= author.last_name %></td>
          <td><%= author.nacionality %></td>
          <td><%= author.review %></td>
          <td><%= link_to 'Show', author %></td>
          <td><%= link_to 'Edit', edit_author_path(author) %></td>
          <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Author', new_author_path %>
</div>

app/views/authors/new.html.erb
<div class="container">
  <h1>New Author</h1>

  <%= render 'form', author: @author %>

  <%= link_to 'Back', authors_path %>
</div>

app/views/authors/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Author <span class="btn btn-xs btn-info"><%= link_to "Show books", author_books_path(@author) %></span></h1>

  <p>
    <strong>Name:</strong>
    <%= @author.name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= @author.last_name %>
  </p>

  <p>
    <strong>Nacionality:</strong>
    <%= @author.nacionality %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= @author.review %>
  </p>

  <%= link_to 'Edit', edit_author_path(@author) %> |
  <%= link_to 'Back', authors_path %>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :editorial %>
    <%= form.text_field :editorial, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :year_edition %>
    <%= form.text_field :year_edition, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :isbn %>
    <%= form.text_field :isbn, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :author_id %>
    <%= select_tag "book[author_id]", options_from_collection_for_select(@authors, "id", "name"), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :shelf_id %>
    <%= select_tag "book[shelf_id]", options_from_collection_for_select(@shelves, "id", "pasillo"), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :num_edition %>
    <%= form.text_field :num_edition, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-xs btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <h1>Editing Book</h1>

  <%= render 'form', book: @book %>

  <%= link_to 'Show', @book %> |
  <%= link_to 'Back', books_path %>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1><%=@title%></h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Editorial</th>
        <th>Year edition</th>
        <th>Isbn</th>
        <th>Author</th>
        <th>Shelf</th>
        <th>Num edition</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.editorial %></td>
          <td><%= book.year_edition %></td>
          <td><%= book.isbn %></td>
          <td><%= book.author.name %></td>
          <td>(<%= book.shelf.id%>) - <%= book.shelf.pasillo %></td>
          <td><%= book.num_edition %></td>
          <td><%= link_to 'Show', book %></td>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Book', new_book_path %>
</div>

app/views/books/new.html.erb
<div class="container">
  <h1>New Book</h1>

  <%= render 'form', book: @book %>

  <%= link_to 'Back', books_path %>
</div>

app/views/books/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1><%= @book.title %></h1>

  <p>
    <strong>Editorial:</strong>
    <%= @book.editorial %>
  </p>

  <p>
    <strong>Year edition:</strong>
    <%= @book.year_edition %>
  </p>

  <p>
    <strong>Isbn:</strong>
    <%= @book.isbn %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= @book.author.name %>
    <%= link_to "Show author", author_path(@book.author) %>
    <%= link_to "Show more books by #{@book.author.name}", author_books_path(@book.author)%>
  </p>

  <p>
    <strong>Shelf:</strong>
    <%= @book.shelf.pasillo %>
    <%= link_to "Show shelf", shelf_path(@book.shelf) %>
    <%= link_to "Show more books", shelf_books_path(@book.shelf)%>
  </p>

  <p>
    <strong>Num edition:</strong>
    <%= @book.num_edition %>
  </p>

  <%= link_to 'Edit', edit_book_path(@book) %> |
  <%= link_to 'Back', books_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgilGob</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shelves/_form.html.erb
<%= form_with(model: shelf, local: true) do |form| %>
  <% if shelf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shelf.errors.count, "error") %> prohibited this shelf from being saved:</h2>

      <ul>
      <% shelf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pasillo %>
    <%= form.text_field :pasillo, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :levels %>
    <%= form.text_field :levels, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-xs btn-success" %>
  </div>
<% end %>

app/views/shelves/edit.html.erb
<div class="container">
  <h1>Editing Shelf</h1>

  <%= render 'form', shelf: @shelf %>

  <%= link_to 'Show', @shelf %> |
  <%= link_to 'Back', shelves_path %>
</div>

app/views/shelves/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Shelves</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Pasillo</th>
        <th>Levels</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @shelves.each do |shelf| %>
        <tr>
          <td><%= shelf.pasillo %></td>
          <td><%= shelf.levels %></td>
          <td><%= link_to 'Show', shelf %></td>
          <td><%= link_to 'Edit', edit_shelf_path(shelf) %></td>
          <td><%= link_to 'Destroy', shelf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Shelf', new_shelf_path %>
</div>

app/views/shelves/new.html.erb
<div class="container">
  <h1>New Shelf</h1>

  <%= render 'form', shelf: @shelf %>

  <%= link_to 'Back', shelves_path %>
</div>

app/views/shelves/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Shelf <span class="btn btn-xs btn-info"><%= link_to "Show books", shelf_books_path(@shelf)%></span></h1>
  <p>
    <strong>Pasillo:</strong>
    <%= @shelf.pasillo %>
  </p>

  <p>
    <strong>Levels:</strong>
    <%= @shelf.levels %>
  </p>

  <%= link_to 'Edit', edit_shelf_path(@shelf) %> |
  <%= link_to 'Back', shelves_path %>
</div>